apiVersion: "greenplum.pivotal.io/v1"
kind: "GreenplumCluster"
metadata:
  name: xiaolong-greenplum
spec:
  masterAndStandby:
    hostBasedAuthentication: |
      # host   all   gpadmin   0.0.0.0/0   zdbAuth
    memory: "800Mi"
    cpu: "0.5"
    storageClassName: hostpath
    storage: 1G
    workerSelector: {}
  segments:
    primarySegmentCount: 1
    memory: "800Mi"
    cpu: "0.5"
    storageClassName: hostpath
    storage: 2G
    workerSelector: {}
